const securityQuestions = {
  mcq: [
    {
      id: 1,
      type: "mcq",
      category: "security",
      question:
        "Which attack allows execution of malicious JavaScript in a victim's browser?",
      options: ["SQL Injection", "XSS", "CSRF", "MITM"],
      correctAnswer: "XSS",
    },
    {
      id: 2,
      type: "mcq",
      category: "security",
      question: "Which vulnerability allows attackers to run system commands?",
      options: ["Clickjacking", "Command Injection", "XSS", "Phishing"],
      correctAnswer: "Command Injection",
    },
    {
      id: 3,
      type: "mcq",
      category: "security",
      question: "CSRF exploits which weakness?",
      options: [
        "Weak encryption",
        "Trusted session",
        "DNS flaw",
        "Weak passwords",
      ],
      correctAnswer: "Trusted session",
    },
    {
      id: 4,
      type: "mcq",
      category: "security",
      question: "Uploading executable files without validation leads to?",
      options: ["SQL Injection", "RCE", "Phishing", "DoS"],
      correctAnswer: "RCE",
    },
    {
      id: 5,
      type: "mcq",
      category: "security",
      question: "Which attack steals authentication cookies?",
      options: ["XSS", "MITM", "Phishing", "CSRF"],
      correctAnswer: "XSS",
    },
    {
      id: 36,
      type: "mcq",
      category: "networking",
      question: "Which protocol converts domain names to IP addresses?",
      options: ["HTTP", "DNS", "FTP", "SMTP"],
      correctAnswer: "DNS",
    },
    {
      id: 37,
      type: "mcq",
      category: "networking",
      question: "Fast but unreliable protocol?",
      options: ["TCP", "UDP", "ICMP", "ARP"],
      correctAnswer: "UDP",
    },
    {
      id: 62,
      type: "mcq",
      category: "security",
      question: "A JWT token is stored in LocalStorage. Why is this dangerous?",
      options: [
        "SQL Injection risk",
        "XSS can steal the token",
        "Token expires faster",
        "Causes CSRF attacks",
      ],
      correctAnswer: "XSS can steal the token",
    },
    {
      id: 63,
      type: "mcq",
      category: "security",
      question:
        "A cookie is marked Secure but NOT HttpOnly. What is the biggest risk?",
      options: [
        "CSRF",
        "XSS stealing cookies",
        "SQL Injection",
        "Packet sniffing",
      ],
      correctAnswer: "XSS stealing cookies",
    },
    {
      id: 64,
      type: "mcq",
      category: "security",
      question:
        "An attacker forces a victim to use a known session ID. What is this attack called?",
      options: [
        "Session Hijacking",
        "Session Fixation",
        "Brute Force",
        "Token Replay",
      ],
      correctAnswer: "Session Fixation",
    },
    {
      id: 65,
      type: "mcq",
      category: "security",
      question:
        "A server blocks .exe but allows .php.jpg. What is the real risk?",
      options: [
        "SQL Injection",
        "Remote Code Execution",
        "CSRF",
        "Open Redirect",
      ],
      correctAnswer: "Remote Code Execution",
    },
    {
      id: 66,
      type: "mcq",
      category: "networking",
      question:
        "Multiple users share one public IP via NAT. How does the router distinguish sessions?",
      options: ["MAC Address", "Port Numbers", "DNS Records", "TTL Values"],
      correctAnswer: "Port Numbers",
    },
    {
      id: 67,
      type: "mcq",
      category: "security",
      question:
        "CSP blocks inline JS but allows scripts from trusted.com. What could still allow XSS?",
      options: [
        "Uploading malicious script to trusted domain",
        "Blocking cookies",
        "Enabling HTTPS",
        "Using DNSSEC",
      ],
      correctAnswer: "Uploading malicious script to trusted domain",
    },
    {
      id: 68,
      type: "mcq",
      category: "security",
      question:
        "If cookies are set to SameSite=Strict, what attack is reduced?",
      options: ["XSS", "SQL Injection", "CSRF", "Brute Force"],
      correctAnswer: "CSRF",
    },
    {
      id: 69,
      type: "mcq",
      category: "networking",
      question: "TCP slows down after packet loss. Why?",
      options: [
        "Encryption overhead",
        "Congestion control mechanism",
        "DNS resolution delay",
        "Firewall filtering",
      ],
      correctAnswer: "Congestion control mechanism",
    },
    {
      id: 70,
      type: "mcq",
      category: "security",
      question:
        "A company uses a reverse proxy in front of its web server. Which of the following is the MOST important security risk if the proxy is misconfigured?",
      options: [
        "Faster DNS resolution",
        "Exposure of internal server IPs",
        "Increased HTTPS encryption",
        "Improved load balancing",
      ],
      correctAnswer: "Exposure of internal server IPs",
    },
    {
      id: 71,
      type: "mcq",
      category: "networking",
      question:
        "I live in the Data Link layer. I map your IP to a physical address. If I am 'Poisoned,' your traffic comes to me instead of the router. What protocol am I?",
      options: ["DNS", "DHCP", "ARP", "ICMP"],
      correctAnswer: "ARP",
    },
    {
      id: 74,
      type: "mcq",
      category: "networking",
      question:
        "I provide a 'best effort' delivery. I don't care if the packets arrive in order or even if they arrive at all. I'm fast, lean, and great for gaming or streaming. What protocol am I?",
      options: ["TCP", "UDP", "SSH", "FTP"],
      correctAnswer: "UDP",
    },
    {
      id: 75,
      type: "mcq",
      category: "networking",
      question:
        "If your IP is 192.168.1.1 and your subnet mask is 255.255.255.0, how many usable host addresses do you have in this little neighborhood?",
      options: ["256", "254", "512", "128"],
      correctAnswer: "254",
    },
    {
      id: 77,
      type: "mcq",
      category: "networking",
      question:
        "I replaced Telnet because I encrypt everything. I usually live on Port 22. What am I?",
      options: ["SSL", "SSH", "SFTP", "SNMP"],
      correctAnswer: "SSH",
    },
    {
      id: 78,
      type: "mcq",
      category: "networking",
      question:
        "In a networking packet, which part contains the actual data (like your message or a piece of an image) rather than the routing information?",
      options: ["Header", "Footer", "Payload", "Checksum"],
      correctAnswer: "Payload",
    },
    {
      id: 79,
      type: "mcq",
      category: "networking",
      question:
        "Which type of firewall looks at the state of active connections rather than just looking at individual packets in isolation?",
      options: [
        "Packet Filter",
        "Stateful Inspection",
        "Proxy Firewall",
        "Next-Gen Firewall",
      ],
      correctAnswer: "Stateful Inspection",
    },
    {
      id: 80,
      type: "mcq",
      category: "networking",
      question:
        "I sit at the edge of your network. I look at every packet coming in and decide who is allowed to enter and who is blocked based on a set of rules. What am I?",
      options: ["Switch", "Hub", "Firewall", "Repeater"],
      correctAnswer: "Firewall",
    },
    {
      id: 83,
      type: "mcq",
      category: "dsa",
      question: "Which problem CANNOT be solved greedily?",
      options: [
        "Fractional Knapsack",
        "Dijkstra's shortest path",
        "0-1 Knapsack",
        "Huffman coding",
      ],
      correctAnswer: "0-1 Knapsack",
    },
    {
      id: 87,
      type: "mcq",
      category: "dsa",
      question: "The Master Theorem applies to recurrences of the form:",
      options: [
        "T(n) = aT(n/b) + f(n)",
        "T(n) = T(n-1) + T(n-2)",
        "T(n) = T(n/2) + n",
        "All of the above",
      ],
      correctAnswer: "T(n) = aT(n/b) + f(n)",
    },
    {
      id: 88,
      type: "mcq",
      category: "bug-fixing",
      question: "What causes a stack overflow error?",
      options: [
        "Infinite recursion",
        "Large array allocation",
        "Memory leak",
        "Division by zero",
      ],
      correctAnswer: "Infinite recursion",
    },
    {
      id: 91,
      type: "mcq",
      category: "security",
      question: "Which of these is NOT a method to prevent SQL injection?",
      options: [
        "Input validation",
        "Using prepared statements",
        "Escaping special characters",
        "Using GET instead of POST",
      ],
      correctAnswer: "Using GET instead of POST",
    },
    {
      id: 92,
      type: "mcq",
      category: "dsa",
      question:
        "Which sorting algorithm has the best average-case time complexity?",
      options: [
        "Bubble Sort",
        "Insertion Sort",
        "Merge Sort",
        "Selection Sort",
      ],
      correctAnswer: "Merge Sort",
    },
    {
      id: 93,
      type: "mcq",
      category: "dsa",
      question: "Which traversal of a BST gives sorted output?",
      options: ["Preorder", "Postorder", "Inorder", "Level order"],
      correctAnswer: "Inorder",
    },
    {
      id: 94,
      type: "mcq",
      category: "dsa",
      question: "A circular queue helps in:",
      options: [
        "Avoiding overflow",
        "Better memory utilization",
        "Faster sorting",
        "Reducing recursion",
      ],
      correctAnswer: "Better memory utilization",
    },
    {
      id: 95,
      type: "mcq",
      category: "dsa",
      question: "Which data structure is used in BFS?",
      options: ["Stack", "Queue", "Heap", "Tree"],
      correctAnswer: "Queue",
    },
    {
      id: 96,
      type: "mcq",
      category: "dsa",
      question: "Which of the following has the worst space complexity?",
      options: ["Merge Sort", "Quick Sort", "Heap Sort", "Selection Sort"],
      correctAnswer: "Merge Sort",
    },
    {
      id: 97,
      type: "mcq",
      category: "bug-fixing",
      question: "A bug that causes the program to crash is called:",
      options: [
        "Syntax error",
        "Logical error",
        "Runtime error",
        "Semantic error",
      ],
      correctAnswer: "Runtime error",
    },
    {
      id: 98,
      type: "mcq",
      category: "dsa",
      question: "Which data structure is best for implementing recursion?",
      options: ["Queue", "Stack", "Heap", "Linked List"],
      correctAnswer: "Stack",
    },
    {
      id: 99,
      type: "mcq",
      category: "bug-fixing",
      question: "Dangling pointer is related to:",
      options: ["Stack", "Heap", "Memory", "Queue"],
      correctAnswer: "Memory",
    },
    {
      id: 100,
      type: "mcq",
      category: "bug-fixing",
      question: "What is the default return type of malloc() in C?",
      options: ["int", "void*", "char*", "float"],
      correctAnswer: "void*",
    },
    {
      id: 101,
      type: "mcq",
      category: "bug-fixing",
      question: "Which bug is hardest to detect?",
      options: [
        "Syntax error",
        "Runtime error",
        "Logical error",
        "Compilation error",
      ],
      correctAnswer: "Logical error",
    },
    {
      id: 102,
      type: "mcq",
      category: "dsa",
      question: "Which traversal uses a queue?",
      options: ["DFS", "BFS", "Inorder", "Postorder"],
      correctAnswer: "BFS",
    },
    {
      id: 103,
      type: "mcq",
      category: "dsa",
      question: "What is the time complexity of heap insertion?",
      options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
      correctAnswer: "O(log n)",
    },
    {
      id: 104,
      type: "mcq",
      category: "dsa",
      question: "Which is NOT an application of stack?",
      options: [
        "Function calls",
        "Undo operation",
        "BFS traversal",
        "Expression evaluation",
      ],
      correctAnswer: "BFS traversal",
    },
    {
      id: 105,
      type: "mcq",
      category: "bug-fixing",
      question: "Which of the following causes memory leak?",
      options: [
        "Unused variables",
        "Not freeing allocated memory",
        "Infinite loop",
        "Syntax error",
      ],
      correctAnswer: "Not freeing allocated memory",
    },
    {
      id: 106,
      type: "mcq",
      category: "dsa",
      question: "Which sorting algorithm is in-place?",
      options: ["Merge Sort", "Quick Sort", "Counting Sort", "Radix Sort"],
      correctAnswer: "Quick Sort",
    },
    {
      id: 107,
      type: "mcq",
      category: "dsa",
      question: "Which graph traversal uses recursion?",
      options: ["BFS", "DFS", "Prim", "Dijkstra"],
      correctAnswer: "DFS",
    },
    {
      id: 108,
      type: "mcq",
      category: "bug-fixing",
      question: "What does segmentation fault indicate?",
      options: [
        "Syntax error",
        "Illegal memory access",
        "Infinite loop",
        "Deadlock",
      ],
      correctAnswer: "Illegal memory access",
    },
    {
      id: 109,
      type: "mcq",
      category: "dsa",
      question: "Which algorithm works well for dense graphs?",
      options: ["Prim", "Kruskal", "DFS", "BFS"],
      correctAnswer: "Prim",
    },
    {
      id: 110,
      type: "mcq",
      category: "dsa",
      question: "Which data structure is used in recursion internally?",
      options: ["Heap", "Queue", "Stack", "Graph"],
      correctAnswer: "Stack",
    },
    {
      id: 111,
      type: "mcq",
      category: "dsa",
      question: "What is the height of a balanced binary tree?",
      options: ["O(n)", "O(log n)", "O(1)", "O(n log n)"],
      correctAnswer: "O(log n)",
    },
    {
      id: 112,
      type: "mcq",
      category: "bug-fixing",
      question: "What is dead code?",
      options: [
        "Code with syntax error",
        "Code never executed",
        "Infinite loop",
        "Recursive code",
      ],
      correctAnswer: "Code never executed",
    },
    {
      id: 113,
      type: "mcq",
      category: "dsa",
      question: "Which algorithm finds all-pairs shortest paths?",
      options: ["Dijkstra", "Floyd-Warshall", "Bellman-Ford", "BFS"],
      correctAnswer: "Floyd-Warshall",
    },
    {
      id: 114,
      type: "mcq",
      category: "bug-fixing",
      question: "Which bug causes incorrect output but no crash?",
      options: [
        "Runtime error",
        "Syntax error",
        "Logical error",
        "Compiler error",
      ],
      correctAnswer: "Logical error",
    },
    {
      id: 115,
      type: "mcq",
      category: "dsa",
      question: "Which algorithm is used for cycle detection?",
      options: ["DFS", "BFS", "Dijkstra", "Heap"],
      correctAnswer: "DFS",
    },
    {
      id: 155,
      type: "mcq",
      category: "dsa",
      question:
        "Which data structure is best for implementing undo/redo operations?",
      options: ["Queue", "Stack", "Tree", "Graph"],
      correctAnswer: "Stack",
    },
    {
      id: 156,
      type: "mcq",
      category: "dsa",
      question: "Which algorithm is used to detect negative weight cycles?",
      options: ["Dijkstra", "Prim", "Bellman-Ford", "DFS"],
      correctAnswer: "Bellman-Ford",
    },
    {
      id: 157,
      type: "mcq",
      category: "dsa",
      question: "Which traversal is used to delete a tree?",
      options: ["Inorder", "Preorder", "Postorder", "Level order"],
      correctAnswer: "Postorder",
    },
    {
      id: 162,
      type: "mcq",
      category: "crypto",
      question:
        "If @ means +, # means −, $ means ×, * means ÷, then the value of 18 $ 2 @ 6 * 3 # 4 is:",
      options: ["14", "16", "18", "20"],
      correctAnswer: "16",
    },
    {
      id: 163,
      type: "mcq",
      category: "crypto",
      question:
        "If P means ÷, Q means ×, R means +, S means −, then 64 P 8 Q 2 R 5 S 3 = ?",
      options: ["18", "20", "22", "24"],
      correctAnswer: "24",
    },
    {
      id: 164,
      type: "mcq",
      category: "crypto",
      question:
        "In a certain code: 12 = stop smoking, 59 = injurious habit. Which digit is most likely the code for 'habit'?",
      options: ["1", "2", "5", "9"],
      correctAnswer: "5",
    },
    {
      id: 165,
      type: "mcq",
      category: "crypto",
      question:
        "In a certain language: go home now = 81 42 19, go school today = 81 77 63. What is the code for go?",
      options: ["19", "42", "63", "81"],
      correctAnswer: "81",
    },
    {
      id: 166,
      type: "mcq",
      category: "crypto",
      question:
        "If A = 1, B = 2, … Z = 26 and word is coded as sum of letters, then code of PEACE is:",
      options: ["29", "32", "34", "36"],
      correctAnswer: "36",
    },
    {
      id: 167,
      type: "mcq",
      category: "crypto",
      question:
        "If reverse alphabet is used (A=26, B=25…Z=1), the code for DATE is:",
      options: ["38", "42", "46", "50"],
      correctAnswer: "38",
    },
    {
      id: 168,
      type: "mcq",
      category: "crypto",
      question: "If each letter is shifted +2 (A→C), then 'CALL' becomes:",
      options: ["ECNN", "ECPP", "ECNN", "ECAA"],
      correctAnswer: "ECNN",
    },
    {
      id: 169,
      type: "mcq",
      category: "crypto",
      question:
        "In a code, vowels are replaced by the next vowel (A→E→I→O→U→A), consonants unchanged. Then NO becomes:",
      options: ["NA", "NU", "NA", "NO"],
      correctAnswer: "NU",
    },
    {
      id: 170,
      type: "mcq",
      category: "crypto",
      question:
        "If word code is formed by (first letter + last letter) positions, then code of WATER is:",
      options: ["41", "44", "46", "49"],
      correctAnswer: "44",
    },
    {
      id: 171,
      type: "mcq",
      category: "crypto",
      question: "If 7 → @, 3 → #, 1 → %, 9 → &, then code for 7319 is:",
      options: ["@#%&", "@%#&", "#@%&", "@#&%"],
      correctAnswer: "@#%&",
    },
    {
      id: 172,
      type: "mcq",
      category: "crypto",
      question:
        "In a coding scheme: 146 = adopt good habits, 468 = adopt healthy life. Code for adopt is:",
      options: ["1", "4", "6", "8"],
      correctAnswer: "4",
    },
    {
      id: 173,
      type: "mcq",
      category: "crypto",
      question: "Using the same scheme, code for habits is:",
      options: ["1", "4", "6", "Cannot be determined"],
      correctAnswer: "6",
    },
    {
      id: 174,
      type: "mcq",
      category: "crypto",
      question:
        "If TREAT and TEAR share common code symbol ⊕, what is the most likely code for common letters between them?",
      options: ["TR", "TEA", "TE", "AT"],
      correctAnswer: "TE",
    },
    {
      id: 175,
      type: "mcq",
      category: "crypto",
      question:
        "If 'OR' is always coded as the middle digit of a 3-digit code, then in OR YOU GO = 124, code for OR is:",
      options: ["1", "2", "4", "cannot say"],
      correctAnswer: "2",
    },
    {
      id: 176,
      type: "mcq",
      category: "crypto",
      question:
        "If 'MANGOES' is coded by writing letters in reverse and removing vowels, code is:",
      options: ["SGNM", "SNGM", "SNGM", "SNGS"],
      correctAnswer: "SNGM",
    },
    {
      id: 177,
      type: "mcq",
      category: "crypto",
      question:
        "If 'CALL' is coded as C1 A1 L2 (letter + frequency), then code of 'BALLOON' is:",
      options: [
        "B1 A1 L2 O2 N1",
        "B1 A1 L2 O2 N2",
        "B1 A1 L3 O2 N1",
        "B1 A1 L2 O3 N1",
      ],
      correctAnswer: "B1 A1 L2 O2 N1",
    },
    {
      id: 178,
      type: "mcq",
      category: "crypto",
      question:
        "If a word is coded as: (number of letters)(number of vowels), then code of 'PEACE' is:",
      options: ["52", "53", "54", "55"],
      correctAnswer: "53",
    },
    {
      id: 179,
      type: "mcq",
      category: "crypto",
      question:
        "If a number is coded as sum of its digits ×2, then code of 507 is:",
      options: ["10", "12", "14", "24"],
      correctAnswer: "24",
    },
    {
      id: 180,
      type: "mcq",
      category: "crypto",
      question: "If 'STOP' is coded as TQRS (each letter +1), then 'SMOKE' is:",
      options: ["TNP LF", "TNPLF", "TNPLG", "TNPKE"],
      correctAnswer: "TNPLF",
    },
    {
      id: 181,
      type: "mcq",
      category: "crypto",
      question:
        "If symbols mean: + → ÷, − → ×, × → +, ÷ → − then value of 12 + 3 − 2 × 5 ÷ 1 is:",
      options: ["7", "9", "11", "13"],
      correctAnswer: "9",
    },
    {
      id: 201,
      type: "mcq",
      category: "logic",
      question:
        "A is 8 m east of B. B is 6 m north of C. C is 4 m west of D. D is 5 m south of E. E is in which direction of A?",
      options: ["North-East", "South-East", "South-West", "North-West"],
      correctAnswer: "South-East",
    },
    {
      id: 202,
      type: "mcq",
      category: "logic",
      question:
        "P walks 10 m north, turns right 5 m, turns right 10 m, turns left 3 m. P is how far and in which direction from start?",
      options: ["2 m East", "2 m West", "3 m East", "3 m West"],
      correctAnswer: "2 m East",
    },
    {
      id: 203,
      type: "mcq",
      category: "logic",
      question:
        "If X is facing north, turns right, then right, then left, then left. Final direction?",
      options: ["North", "South", "East", "West"],
      correctAnswer: "West",
    },
    {
      id: 204,
      type: "mcq",
      category: "logic",
      question:
        "A is to the north of B. C is to the east of B. D is to the south of C. D is in which direction of A?",
      options: ["South", "South-East", "East", "South-West"],
      correctAnswer: "South-East",
    },
    {
      id: 205,
      type: "mcq",
      category: "logic",
      question:
        "In a row, E is second to the left of F. A is fourth to the right of E. C is between A and E. Who is in the middle?",
      options: ["F", "E", "C", "A"],
      correctAnswer: "C",
    },
    {
      id: 206,
      type: "mcq",
      category: "logic",
      question:
        "R is 6 km towards west of P. K is 5 km towards south of R. K is in which direction of P?",
      options: ["South-West", "South-East", "North-West", "West"],
      correctAnswer: "South-West",
    },
    {
      id: 207,
      type: "mcq",
      category: "logic",
      question:
        "A person walks 2 km east, 3 km north, 2 km west, 1 km south. Shortest distance from start?",
      options: ["1 km", "2 km", "3 km", "4 km"],
      correctAnswer: "2 km",
    },
    {
      id: 208,
      type: "mcq",
      category: "logic",
      question:
        "S is facing East. T is left of S. U is left of T. U is in which direction of S?",
      options: ["North", "West", "South", "North-West"],
      correctAnswer: "West",
    },
    {
      id: 209,
      type: "mcq",
      category: "logic",
      question:
        "A is 3 m north of P. Q is 4 m east of A. R is 2 m south of Q. R is how far from P?",
      options: ["3 m", "4 m", "5 m", "6 m"],
      correctAnswer: "5 m",
    },
    {
      id: 210,
      type: "mcq",
      category: "logic",
      question:
        "If D is directly north of B, and A is directly west of B, then A is in which direction of D?",
      options: ["North-West", "South-West", "North-East", "South-East"],
      correctAnswer: "South-West",
    },
    {
      id: 211,
      type: "mcq",
      category: "logic",
      question:
        "How many people are standing in a straight line (all facing north)? I. Only one person is between S and D; D is immediately right of P. II. Exactly three people are between M and P; S is to the left of M.",
      options: [
        "Statement I alone sufficient",
        "Statement II alone sufficient",
        "Both I & II together sufficient",
        "Even both insufficient",
      ],
      correctAnswer: "Even both insufficient",
    },
    {
      id: 212,
      type: "mcq",
      category: "logic",
      question:
        "What is the distance from X to Y? I. X is 20 cm to the right of Z; Z is 10 cm left of Y. II. The distance from X to Z equals half the distance from Y to Z.",
      options: [
        "Statement I alone sufficient",
        "Statement II alone sufficient",
        "Both I & II together sufficient",
        "Even both insufficient",
      ],
      correctAnswer: "Both I & II together sufficient",
    },
    {
      id: 213,
      type: "mcq",
      category: "logic",
      question:
        "In which direction is point T from point P? I. P is 7 m to the south-west of Q; Q is north of T. II. P, Q and T form a straight line.",
      options: [
        "Statement I alone sufficient",
        "Statement II alone sufficient",
        "Both I & II together sufficient",
        "Even both insufficient",
      ],
      correctAnswer: "Statement II alone sufficient",
    },
    {
      id: 214,
      type: "mcq",
      category: "logic",
      question:
        "Who is facing East? I. S is on the right of K and is facing East. II. Y is directly north of Z and Z is west of X.",
      options: [
        "Statement I alone sufficient",
        "Statement II alone sufficient",
        "Both I & II together sufficient",
        "Even both insufficient",
      ],
      correctAnswer: "Statement I alone sufficient",
    },
    {
      id: 215,
      type: "mcq",
      category: "logic",
      question:
        "Which city is north of City A? I. City B is west of City D; City C is east of City B. II. City A is north of City C.",
      options: [
        "Statement I alone sufficient",
        "Statement II alone sufficient",
        "Both I & II together sufficient",
        "Even both insufficient",
      ],
      correctAnswer: "Both I & II together sufficient",
    },
    {
      id: 216,
      type: "mcq",
      category: "logic",
      question:
        "In a class, Swita ranks 4th from top and Arsh is 2 ranks above Swita. Total students are 40. Arsh's rank from bottom is:",
      options: ["33", "34", "35", "36"],
      correctAnswer: "35",
    },
    {
      id: 217,
      type: "mcq",
      category: "logic",
      question:
        "A, B, C, D, E are in a row. C is not at an end. B is to the left of C. E is at the right end. Who can be in the middle?",
      options: ["A", "B", "C", "D"],
      correctAnswer: "C",
    },
    {
      id: 218,
      type: "mcq",
      category: "logic",
      question:
        "Five friends P,Q,R,S,T have different heights. P is taller than Q but shorter than R. S is not tallest. Who is tallest?",
      options: ["P", "Q", "R", "Cannot be determined"],
      correctAnswer: "Cannot be determined",
    },
    {
      id: 219,
      type: "mcq",
      category: "logic",
      question: "If the series is: 2, 5, 8, 11, __ Missing number is:",
      options: ["12", "13", "14", "15"],
      correctAnswer: "14",
    },
    {
      id: 220,
      type: "mcq",
      category: "logic",
      question: "In the series: 7, 17, 15, 25, 23, __ Next number is:",
      options: ["33", "35", "27", "31"],
      correctAnswer: "33",
    },
  ],

  fillBlanks: [
    {
      id: 6,
      type: "fill",
      category: "security",
      question: "Redirecting users to malicious websites is called?",
      correctAnswer: ["Open Redirect"],
      points: 1,
    },
    {
      id: 7,
      type: "fill",
      category: "security",
      question: "Repeated password guessing is called?",
      correctAnswer: ["Brute Force"],
      points: 1,
    },
    {
      id: 8,
      type: "fill",
      category: "security",
      question: "Exploiting unsafe file upload leads to?",
      correctAnswer: ["Remote Code Execution", "RCE"],
      points: 1,
    },
    {
      id: 9,
      type: "fill",
      category: "security",
      question: "Manipulating SQL queries via input is called?",
      correctAnswer: ["SQL Injection"],
      points: 1,
    },
    {
      id: 10,
      type: "fill",
      category: "security",
      question: "Fake websites that steal credentials cause?",
      correctAnswer: ["Phishing"],
      points: 1,
    },
    {
      id: 11,
      type: "fill",
      category: "security",
      question: "What attack tricks users into clicking hidden elements?",
      correctAnswer: ["Clickjacking"],
      points: 1,
    },
    {
      id: 12,
      type: "fill",
      category: "security",
      question: "Weak session IDs allow?",
      correctAnswer: ["Session Hijacking"],
      points: 1,
    },
    {
      id: 13,
      type: "fill",
      category: "security",
      question: "What vulnerability exposes admin panels publicly?",
      correctAnswer: ["Security Misconfiguration"],
      points: 1,
    },
    {
      id: 14,
      type: "fill",
      category: "security",
      question: "Injecting HTML into a page is called?",
      correctAnswer: ["HTML Injection"],
      points: 1,
    },
    {
      id: 15,
      type: "fill",
      category: "security",
      question: "Intercepting browser-server traffic is called?",
      correctAnswer: ["MITM", "Man in the Middle"],
      points: 1,
    },
    {
      id: 16,
      type: "fill",
      category: "security",
      question: "Injecting scripts into web pages is called ______.",
      correctAnswer: ["XSS", "Cross Site Scripting"],
      points: 1,
    },
    {
      id: 17,
      type: "fill",
      category: "security",
      question: "Unauthorized request exploitation is called ______.",
      correctAnswer: ["CSRF", "Cross Site Request Forgery"],
      points: 1,
    },
    {
      id: 18,
      type: "fill",
      category: "security",
      question: "Uploading unsafe executable files causes ______.",
      correctAnswer: ["RCE", "Remote Code Execution"],
      points: 1,
    },
    {
      id: 19,
      type: "fill",
      category: "security",
      question: "Guessing passwords repeatedly is called ______.",
      correctAnswer: ["Brute Force"],
      points: 1,
    },
    {
      id: 20,
      type: "fill",
      category: "security",
      question: "Exploiting weak login tokens causes ______.",
      correctAnswer: ["Account Takeover"],
      points: 1,
    },
    {
      id: 21,
      type: "fill",
      category: "security",
      question: "Injecting OS commands via input is called ______.",
      correctAnswer: ["Command Injection"],
      points: 1,
    },
    {
      id: 22,
      type: "fill",
      category: "security",
      question: "Fake login pages cause ______ attacks.",
      correctAnswer: ["Phishing"],
      points: 1,
    },
    {
      id: 23,
      type: "fill",
      category: "security",
      question: "Storing malicious scripts in DB is called ______.",
      correctAnswer: ["Stored XSS"],
      points: 1,
    },
    {
      id: 24,
      type: "fill",
      category: "security",
      question: "Unsafe redirects cause ______ vulnerability.",
      correctAnswer: ["Open Redirect"],
      points: 1,
    },
    {
      id: 25,
      type: "fill",
      category: "security",
      question: "Unauthorized API access leads to ______.",
      correctAnswer: ["Broken Access Control"],
      points: 1,
    },
    {
      id: 31,
      type: "fill",
      category: "security",
      question:
        "A user visits an HTTPS site, but the device is infected with malware that installed a fake root certificate. Why is HTTPS no longer fully secure?",
      correctAnswer: ["MITM via trusted fake certificate"],
      points: 1,
    },
    {
      id: 32,
      type: "fill",
      category: "networking",
      question:
        "A real-time game uses TCP instead of UDP. Why can TCP cause worse gameplay even though it's reliable?",
      correctAnswer: ["Retransmissions increase latency", "lag"],
      points: 1,
    },
    {
      id: 38,
      type: "fill",
      category: "networking",
      question: "Reliable data delivery protocol?",
      correctAnswer: ["TCP"],
      points: 1,
    },
    {
      id: 39,
      type: "fill",
      category: "networking",
      question: "Ping uses which protocol?",
      correctAnswer: ["ICMP"],
      points: 1,
    },
    {
      id: 40,
      type: "fill",
      category: "networking",
      question: "Device connecting networks?",
      correctAnswer: ["Router"],
      points: 1,
    },
    {
      id: 41,
      type: "fill",
      category: "networking",
      question: "Default HTTPS port?",
      correctAnswer: ["443"],
      points: 1,
    },
    {
      id: 42,
      type: "fill",
      category: "networking",
      question: "Protocol assigning IP automatically?",
      correctAnswer: ["DHCP"],
      points: 1,
    },
    {
      id: 43,
      type: "fill",
      category: "networking",
      question: "Protocol resolving IP to MAC?",
      correctAnswer: ["ARP"],
      points: 1,
    },
    {
      id: 44,
      type: "fill",
      category: "networking",
      question: "Tool to capture packets?",
      correctAnswer: ["Wireshark"],
      points: 1,
    },
    {
      id: 45,
      type: "fill",
      category: "networking",
      question: "Packet dropped when TTL reaches?",
      correctAnswer: ["Zero", "0"],
      points: 1,
    },
    {
      id: 46,
      type: "fill",
      category: "networking",
      question: "NAT allows sharing one public?",
      correctAnswer: ["IP"],
      points: 1,
    },
    {
      id: 47,
      type: "fill",
      category: "networking",
      question: "SMTP is used for?",
      correctAnswer: ["Email"],
      points: 1,
    },
    {
      id: 48,
      type: "fill",
      category: "networking",
      question: "Protocol for file transfer?",
      correctAnswer: ["FTP"],
      points: 1,
    },
    {
      id: 49,
      type: "fill",
      category: "networking",
      question: "Private IP range 192.168.x.x means?",
      correctAnswer: ["Private Network"],
      points: 1,
    },
    {
      id: 50,
      type: "fill",
      category: "networking",
      question: "Protocol encrypting HTTPS traffic?",
      correctAnswer: ["TLS", "SSL"],
      points: 1,
    },
    {
      id: 51,
      type: "fill",
      category: "networking",
      question: "DNS converts domain names to ______.",
      correctAnswer: ["IP addresses", "IP"],
      points: 1,
    },
    {
      id: 52,
      type: "fill",
      category: "networking",
      question: "UDP does not guarantee packet ______.",
      correctAnswer: ["Delivery"],
      points: 1,
    },
    {
      id: 53,
      type: "fill",
      category: "networking",
      question: "Router works at ______ layer.",
      correctAnswer: ["Network"],
      points: 1,
    },
    {
      id: 54,
      type: "fill",
      category: "networking",
      question: "ARP maps IP to ______ address.",
      correctAnswer: ["MAC"],
      points: 1,
    },
    {
      id: 55,
      type: "fill",
      category: "networking",
      question: "DHCP assigns ______ automatically.",
      correctAnswer: ["IP"],
      points: 1,
    },
    {
      id: 56,
      type: "fill",
      category: "networking",
      question: "TCP ensures ______ data delivery.",
      correctAnswer: ["Reliable"],
      points: 1,
    },
    {
      id: 57,
      type: "fill",
      category: "networking",
      question: "TTL prevents packets from ______ looping.",
      correctAnswer: ["Infinite"],
      points: 1,
    },
    {
      id: 58,
      type: "fill",
      category: "networking",
      question: "VPN encrypts traffic across ______ networks.",
      correctAnswer: ["Public"],
      points: 1,
    },
    {
      id: 59,
      type: "fill",
      category: "networking",
      question: "Switch forwards data inside a ______.",
      correctAnswer: ["LAN"],
      points: 1,
    },
    {
      id: 60,
      type: "fill",
      category: "networking",
      question: "ICMP is used for network ______.",
      correctAnswer: ["Diagnostics"],
      points: 1,
    },
    {
      id: 61,
      type: "fill",
      category: "security",
      question:
        "A user types a correct website URL but is redirected to a fake one. Even without hacking the server, how is this possible?",
      correctAnswer: ["DNS Cache Poisoning"],
      points: 1,
    },
    {
      id: 81,
      type: "fill",
      category: "dsa",
      question: "The space complexity of Merge Sort is ______.",
      correctAnswer: ["O(n)"],
      points: 1,
    },
    {
      id: 82,
      type: "fill",
      category: "bug-fixing",
      question:
        "A ______ variable is one that is accessible only within the block where it's declared.",
      correctAnswer: ["Local"],
      points: 1,
    },
    {
      id: 84,
      type: "fill",
      category: "web",
      question:
        "A ______ is a small piece of data stored on the client's computer by the web browser.",
      correctAnswer: ["Cookie"],
      points: 1,
    },
    {
      id: 85,
      type: "fill",
      category: "web",
      question:
        "The ______ object model represents the structure of an HTML document.",
      correctAnswer: ["DOM", "Document Object Model"],
      points: 1,
    },
    {
      id: 86,
      type: "fill",
      category: "dsa",
      question:
        "The ______ property in ACID ensures that database transactions are treated as a single unit.",
      correctAnswer: ["Atomicity"],
      points: 1,
    },
    {
      id: 89,
      type: "fill",
      category: "dsa",
      question:
        "The ______ data structure supports union and find operations for disjoint sets.",
      correctAnswer: ["Disjoint Set", "Union-Find", "Union Find"],
      points: 1,
    },
    {
      id: 90,
      type: "fill",
      category: "dsa",
      question: "Binary search works only on ______ data.",
      correctAnswer: ["Sorted"],
      points: 1,
    },
    {
      id: 116,
      type: "fill",
      category: "bug-fixing",
      question: "Memory allocated using malloc resides in the ______ segment.",
      correctAnswer: ["Heap"],
      points: 1,
    },
    {
      id: 117,
      type: "fill",
      category: "bug-fixing",
      question: "A ______ error occurs during program execution.",
      correctAnswer: ["Runtime"],
      points: 1,
    },
    {
      id: 118,
      type: "fill",
      category: "dsa",
      question: "DFS uses ______ data structure internally.",
      correctAnswer: ["Stack"],
      points: 1,
    },
    {
      id: 119,
      type: "fill",
      category: "dsa",
      question: "In a BST, left child contains ______ values.",
      correctAnswer: ["Smaller"],
      points: 1,
    },
    {
      id: 120,
      type: "fill",
      category: "bug-fixing",
      question: "A bug caused due to wrong conditions is a ______ error.",
      correctAnswer: ["Logical"],
      points: 1,
    },
    {
      id: 121,
      type: "fill",
      category: "bug-fixing",
      question: "The process of removing errors is called ______.",
      correctAnswer: ["Debugging"],
      points: 1,
    },
    {
      id: 122,
      type: "fill",
      category: "dsa",
      question: "Heap Sort is based on ______ data structure.",
      correctAnswer: ["Heap"],
      points: 1,
    },
    {
      id: 123,
      type: "fill",
      category: "dsa",
      question: "Recursion uses the ______ stack.",
      correctAnswer: ["Call"],
      points: 1,
    },
    {
      id: 124,
      type: "fill",
      category: "bug-fixing",
      question: "A ______ pointer points to freed memory.",
      correctAnswer: ["Dangling"],
      points: 1,
    },
    {
      id: 125,
      type: "fill",
      category: "dsa",
      question: "The best case of binary search is ______.",
      correctAnswer: ["O(1)"],
      points: 1,
    },
    {
      id: 126,
      type: "fill",
      category: "dsa",
      question: "Linked list nodes contain data and ______.",
      correctAnswer: ["Pointer"],
      points: 1,
    },
    {
      id: 127,
      type: "fill",
      category: "dsa",
      question: "BFS is implemented using a ______.",
      correctAnswer: ["Queue"],
      points: 1,
    },
    {
      id: 128,
      type: "fill",
      category: "bug-fixing",
      question: "Infinite recursion leads to ______ error.",
      correctAnswer: ["Stack overflow", "Stack Overflow"],
      points: 1,
    },
    {
      id: 129,
      type: "fill",
      category: "dsa",
      question: "A graph with no cycles is called a ______ graph.",
      correctAnswer: ["Acyclic"],
      points: 1,
    },
    {
      id: 130,
      type: "fill",
      category: "dsa",
      question: "Kruskal's algorithm uses ______ sorting.",
      correctAnswer: ["Edge"],
      points: 1,
    },
    {
      id: 131,
      type: "fill",
      category: "dsa",
      question: "A balanced BST has height ______.",
      correctAnswer: ["O(log n)"],
      points: 1,
    },
    {
      id: 132,
      type: "fill",
      category: "bug-fixing",
      question: "A bug that crashes the program is a ______ error.",
      correctAnswer: ["Runtime"],
      points: 1,
    },
    {
      id: 133,
      type: "fill",
      category: "dsa",
      question: "Hashing is used for ______ searching.",
      correctAnswer: ["Fast"],
      points: 1,
    },
    {
      id: 134,
      type: "fill",
      category: "dsa",
      question: "Dynamic Programming avoids ______ computation.",
      correctAnswer: ["Redundant"],
      points: 1,
    },
    {
      id: 135,
      type: "fill",
      category: "dsa",
      question: "The root of a heap is always the ______ element.",
      correctAnswer: ["Maximum", "Minimum"],
      points: 1,
    },
    {
      id: 136,
      type: "fill",
      category: "bug-fixing",
      question: "A pointer not initialized is called ______ pointer.",
      correctAnswer: ["Wild"],
      points: 1,
    },
    {
      id: 137,
      type: "fill",
      category: "bug-fixing",
      question: "Dead code never gets ______.",
      correctAnswer: ["Executed"],
      points: 1,
    },
    {
      id: 138,
      type: "fill",
      category: "dsa",
      question: "A circular queue solves the problem of ______.",
      correctAnswer: ["Overflow"],
      points: 1,
    },
    {
      id: 139,
      type: "fill",
      category: "dsa",
      question:
        "I store function calls and disappear when they return. Who am I?",
      correctAnswer: ["Stack"],
      points: 1,
    },
    {
      id: 140,
      type: "fill",
      category: "dsa",
      question:
        "I am faster than linear search but need data in order. What am I?",
      correctAnswer: ["Binary Search"],
      points: 1,
    },
    {
      id: 141,
      type: "fill",
      category: "bug-fixing",
      question:
        "I crash programs when recursion forgets to stop. What error am I?",
      correctAnswer: ["Stack overflow", "Stack Overflow"],
      points: 1,
    },
    {
      id: 142,
      type: "fill",
      category: "bug-fixing",
      question:
        "I give correct output only when logic is correct, not syntax. Who am I?",
      correctAnswer: ["Logical Error"],
      points: 1,
    },
    {
      id: 143,
      type: "fill",
      category: "dsa",
      question:
        "I help avoid recalculations by storing past results. Who am I?",
      correctAnswer: ["Dynamic Programming"],
      points: 1,
    },
    {
      id: 144,
      type: "fill",
      category: "dsa",
      question: "I work level by level in a tree. Which traversal am I?",
      correctAnswer: ["Level Order", "BFS"],
      points: 1,
    },
    {
      id: 145,
      type: "fill",
      category: "bug-fixing",
      question: "I waste memory if not freed after use. What problem am I?",
      correctAnswer: ["Memory Leak"],
      points: 1,
    },
    {
      id: 146,
      type: "fill",
      category: "dsa",
      question: "I always choose the locally best option. Which approach am I?",
      correctAnswer: ["Greedy Approach", "Greedy"],
      points: 1,
    },
    {
      id: 147,
      type: "fill",
      category: "dsa",
      question: "I detect cycles and explore deep paths first. Who am I?",
      correctAnswer: ["DFS"],
      points: 1,
    },
    {
      id: 148,
      type: "fill",
      category: "dsa",
      question:
        "I break problems into smaller subproblems and combine results. Who am I?",
      correctAnswer: ["Divide and Conquer"],
      points: 1,
    },
    {
      id: 149,
      type: "fill",
      category: "dsa",
      question:
        "I maintain parent-child relationships using pointers. What structure am I?",
      correctAnswer: ["Tree"],
      points: 1,
    },
    {
      id: 150,
      type: "fill",
      category: "bug-fixing",
      question:
        "I overflow when function calls never end. What structure am I?",
      correctAnswer: ["Stack"],
      points: 1,
    },
    {
      id: 151,
      type: "fill",
      category: "bug-fixing",
      question:
        "I cause wrong output without crashing the program. What bug am I?",
      correctAnswer: ["Logical Error"],
      points: 1,
    },
    {
      id: 152,
      type: "fill",
      category: "dsa",
      question: "I connect nodes with edges and may have cycles. Who am I?",
      correctAnswer: ["Graph"],
      points: 1,
    },
    {
      id: 153,
      type: "fill",
      category: "dsa",
      question: "I keep data in first-in-first-out order. What am I?",
      correctAnswer: ["Queue"],
      points: 1,
    },
    {
      id: 154,
      type: "fill",
      category: "dsa",
      question: "I store addresses instead of values. What structure am I?",
      correctAnswer: ["Pointer-based structure", "Pointer"],
      points: 1,
    },
    {
      id: 158,
      type: "fill",
      category: "dsa",
      question: "I become slow if collisions increase. Who am I?",
      correctAnswer: ["Hash Table"],
      points: 1,
    },
    {
      id: 159,
      type: "fill",
      category: "bug-fixing",
      question:
        "I repeat until condition breaks, or else I run forever. Who am I?",
      correctAnswer: ["Loop"],
      points: 1,
    },
    {
      id: 160,
      type: "fill",
      category: "bug-fixing",
      question:
        "I never shrink, only grow, and waste memory if not careful. Who am I?",
      correctAnswer: ["Memory Leak"],
      points: 1,
    },
    {
      id: 161,
      type: "fill",
      category: "dsa",
      question: "I choose first, regret later if wrong. Which algorithm am I?",
      correctAnswer: ["Greedy Algorithm", "Greedy"],
      points: 1,
    },
    {
      id: 182,
      type: "fill",
      category: "crypto",
      question:
        "If 12 = stop smoking and 59 = injurious habit, then the common idea word is ________.",
      correctAnswer: ["smoking", "habit", "cannot be determined"],
      points: 1,
    },
    {
      id: 183,
      type: "fill",
      category: "crypto",
      question:
        "In go home now = 81 42 19 and go school today = 81 77 63, code for go is ______.",
      correctAnswer: ["81"],
      points: 1,
    },
    {
      id: 184,
      type: "fill",
      category: "crypto",
      question: "Reverse alphabet code: A=26 ... Z=1. Then D = ____, T = ____.",
      correctAnswer: ["23, 7", "D = 23, T = 7", "23 and 7"],
      points: 1,
    },
    {
      id: 185,
      type: "fill",
      category: "crypto",
      question: "If each letter is shifted +2, then CALL → ______.",
      correctAnswer: ["ECNN"],
      points: 1,
    },
    {
      id: 186,
      type: "fill",
      category: "crypto",
      question: "If vowels cycle A→E→I→O→U→A, then NO → ______.",
      correctAnswer: ["NU"],
      points: 1,
    },
    {
      id: 187,
      type: "fill",
      category: "crypto",
      question:
        "If word code is (first letter position + last letter position), then WATER → ______.",
      correctAnswer: ["44"],
      points: 1,
    },
    {
      id: 188,
      type: "fill",
      category: "crypto",
      question: "If 7 → @, 3 → #, 1 → %, 9 → &, then 7319 → ______.",
      correctAnswer: ["@#%&"],
      points: 1,
    },
    {
      id: 189,
      type: "fill",
      category: "crypto",
      question:
        "If a word is coded as (letters)(vowels), then MANGOES → ______.",
      correctAnswer: ["73"],
      points: 1,
    },
    {
      id: 190,
      type: "fill",
      category: "crypto",
      question: "If 'STOP' → 'TUPQ' (each letter +1), then 'GO' → ______.",
      correctAnswer: ["HP", "IQ"],
      points: 1,
    },
    {
      id: 191,
      type: "fill",
      category: "crypto",
      question:
        "If 146 = adopt good habits and 468 = adopt healthy life, then code for adopt is ______.",
      correctAnswer: ["4"],
      points: 1,
    },
    {
      id: 221,
      type: "fill",
      category: "logic",
      question: "If A is 5 m east of B, then B is 5 m ______ of A.",
      correctAnswer: ["west"],
      points: 1,
    },
    {
      id: 222,
      type: "fill",
      category: "logic",
      question: "Facing North, a right turn means facing ______.",
      correctAnswer: ["east"],
      points: 1,
    },
    {
      id: 223,
      type: "fill",
      category: "logic",
      question: "P is south of Q and west of R. So P is ______ of R.",
      correctAnswer: ["west"],
      points: 1,
    },
    {
      id: 224,
      type: "fill",
      category: "logic",
      question:
        "If X is to the left of Y (both facing north), X is to the ______ of Y.",
      correctAnswer: ["west"],
      points: 1,
    },
    {
      id: 225,
      type: "fill",
      category: "logic",
      question:
        "A walks 3 km north and 4 km east. Shortest distance from start is ______ km.",
      correctAnswer: ["5"],
      points: 1,
    },
    {
      id: 226,
      type: "fill",
      category: "logic",
      question:
        "In ranking: If Ravi is 10th from top in a class of 40, then Ravi is ______ from bottom.",
      correctAnswer: ["31st", "31"],
      points: 1,
    },
    {
      id: 227,
      type: "fill",
      category: "logic",
      question:
        "If in a line, E is second to the left of F, then F is second to the ______ of E.",
      correctAnswer: ["right"],
      points: 1,
    },
    {
      id: 228,
      type: "fill",
      category: "logic",
      question:
        "If a series increases by +3 each time starting 2, then 5th term is ______.",
      correctAnswer: ["14"],
      points: 1,
    },
    {
      id: 229,
      type: "fill",
      category: "logic",
      question:
        "In the word 'EDUCATIONAL', number of letters between M and N is ______.",
      correctAnswer: ["1"],
      points: 1,
    },
    {
      id: 230,
      type: "fill",
      category: "logic",
      question:
        "If all vowels are removed from 'BASKETBALL', remaining letters count is ______.",
      correctAnswer: ["9"],
      points: 1,
    },
    {
      id: 241,
      type: "fill",
      category: "crypto",
      question: "If letters are shifted +2 (A→C), then CALL → ______.",
      correctAnswer: ["ECNN"],
      points: 1,
    },
    {
      id: 242,
      type: "fill",
      category: "crypto",
      question: "Using reverse alphabet (A=26 … Z=1), D = ____ and T = ____.",
      correctAnswer: ["23, 7", "D = 23, T = 7", "23 and 7"],
      points: 1,
    },
    {
      id: 243,
      type: "fill",
      category: "crypto",
      question:
        "If code format is (number of letters)(number of vowels), then QUEUE → ____.",
      correctAnswer: ["54"],
      points: 1,
    },
    {
      id: 244,
      type: "fill",
      category: "crypto",
      question:
        "Given mapping: 0→@, 1→#, 2→$, 3→%, 4→&, 5→^, then 230 → ______.",
      correctAnswer: ["$%@"],
      points: 1,
    },
    {
      id: 245,
      type: "fill",
      category: "crypto",
      question: "If @=+ , #=− , $=× , *=÷, then value of 18*3#2 = ______.",
      correctAnswer: ["4"],
      points: 1,
    },
    {
      id: 246,
      type: "fill",
      category: "logic",
      question: "If A is 7 m east of B, then B is 7 m ______ of A.",
      correctAnswer: ["west"],
      points: 1,
    },
    {
      id: 247,
      type: "fill",
      category: "logic",
      question: "Facing North, a right turn means facing ______.",
      correctAnswer: ["east"],
      points: 1,
    },
    {
      id: 248,
      type: "fill",
      category: "logic",
      question:
        "P walks 3 m north and 4 m east. Shortest distance from start = ______ m.",
      correctAnswer: ["5"],
      points: 1,
    },
    {
      id: 249,
      type: "fill",
      category: "logic",
      question:
        "In a class of 40, rank 12th from top is rank ______ from bottom.",
      correctAnswer: ["29th", "29"],
      points: 1,
    },
    {
      id: 250,
      type: "fill",
      category: "logic",
      question: "If X is south-west of Y, then Y is ______ of X.",
      correctAnswer: ["north-east"],
      points: 1,
    },
  ],

  matching: [
    {
      id: 26,
      type: "matching",
      category: "security",
      question: "Match Column A with Column B",
      columnA: [
        { key: "A", value: "CSRF" },
        { key: "B", value: "SQL Injection" },
        { key: "C", value: "XSS" },
      ],
      columnB: [
        { key: "1", value: "Forces unauthorized user actions" },
        { key: "2", value: "Injects malicious scripts" },
        { key: "3", value: "Manipulates database queries" },
      ],
      correctMatches: {
        A: "1",
        B: "3",
        C: "2",
      },
    },
    {
      id: 27,
      type: "matching",
      category: "security",
      question: "Match the Vulnerability with its Impact",
      columnA: [
        { key: "A", value: "Broken Authentication" },
        { key: "B", value: "Open Redirect" },
        { key: "C", value: "Unrestricted File Upload" },
      ],
      columnB: [
        { key: "1", value: "Users redirected to fake websites" },
        { key: "2", value: "Server-side code execution" },
        { key: "3", value: "Account takeover" },
      ],
      correctMatches: {
        A: "3",
        B: "1",
        C: "2",
      },
    },
    {
      id: 28,
      type: "matching",
      category: "security",
      question: "Match the Attack with the Outcome",
      columnA: [
        { key: "A", value: "MITM" },
        { key: "B", value: "Brute Force" },
        { key: "C", value: "Phishing" },
      ],
      columnB: [
        { key: "1", value: "Intercepts network traffic" },
        { key: "2", value: "Password guessing" },
        { key: "3", value: "Credential theft" },
      ],
      correctMatches: {
        A: "1",
        B: "2",
        C: "3",
      },
    },
    {
      id: 29,
      type: "matching",
      category: "security",
      question: "Match the Exploit Type with its Meaning",
      columnA: [
        { key: "A", value: "Clickjacking" },
        { key: "B", value: "Stored XSS" },
        { key: "C", value: "Command Injection" },
      ],
      columnB: [
        { key: "1", value: "Runs malicious scripts from database" },
        { key: "2", value: "Executes system-level commands" },
        { key: "3", value: "Tricks users into clicking hidden UI" },
      ],
      correctMatches: {
        A: "3",
        B: "1",
        C: "2",
      },
    },
    {
      id: 30,
      type: "matching",
      category: "security",
      question: "Match the Security Issue with the Effect",
      columnA: [
        { key: "A", value: "Weak Session Tokens" },
        { key: "B", value: "HTML Injection" },
        { key: "C", value: "Security Misconfiguration" },
      ],
      columnB: [
        { key: "1", value: "Page content manipulation" },
        { key: "2", value: "Session hijacking" },
        { key: "3", value: "Exposed admin panels" },
      ],
      correctMatches: {
        A: "2",
        B: "1",
        C: "3",
      },
    },
    {
      id: 33,
      type: "matching",
      category: "networking",
      question: "Match the Security Concept with Description",
      columnA: [
        { key: "A", value: "VPN" },
        { key: "B", value: "Firewall" },
        { key: "C", value: "TLS" },
      ],
      columnB: [
        { key: "1", value: "Encrypts web traffic" },
        { key: "2", value: "Filters network traffic" },
        { key: "3", value: "Creates secure tunnels" },
      ],
      correctMatches: {
        A: "3",
        B: "2",
        C: "1",
      },
    },
    {
      id: 34,
      type: "matching",
      category: "networking",
      question: "Match the Tool with its Use",
      columnA: [
        { key: "A", value: "Wireshark" },
        { key: "B", value: "Ping" },
        { key: "C", value: "Traceroute" },
      ],
      columnB: [
        { key: "1", value: "Tracks packet route" },
        { key: "2", value: "Tests network connectivity" },
        { key: "3", value: "Captures network packets" },
      ],
      correctMatches: {
        A: "3",
        B: "2",
        C: "1",
      },
    },
    {
      id: 35,
      type: "matching",
      category: "networking",
      question: "Match the Networking Term with Meaning",
      columnA: [
        { key: "A", value: "NAT" },
        { key: "B", value: "TTL" },
        { key: "C", value: "DHCP" },
      ],
      columnB: [
        { key: "1", value: "Limits packet lifetime" },
        { key: "2", value: "Assigns IP addresses automatically" },
        { key: "3", value: "Shares one public IP among many devices" },
      ],
      correctMatches: {
        A: "3",
        B: "1",
        C: "2",
      },
    },
    {
      id: 72,
      type: "matching",
      category: "security",
      question:
        "A JSON Web Token has three parts separated by dots. Match them:",
      columnA: [
        { key: "1", value: "Header" },
        { key: "2", value: "Payload" },
        { key: "3", value: "Signature" },
      ],
      columnB: [
        { key: "A", value: "The actual data (user ID, roles)" },
        { key: "B", value: "Proves the token hasn't been tampered with" },
        { key: "C", value: "Defines the algorithm (e.g., HS256)" },
      ],
      correctMatches: {
        1: "C",
        2: "A",
        3: "B",
      },
    },
    {
      id: 73,
      type: "matching",
      category: "networking",
      question: "Match the service to its standard port number:",
      columnA: [
        { key: "1", value: "22" },
        { key: "2", value: "25" },
        { key: "3", value: "53" },
        { key: "4", value: "443" },
      ],
      columnB: [
        { key: "A", value: "HTTPS" },
        { key: "B", value: "DNS" },
        { key: "C", value: "SSH" },
        { key: "D", value: "SMTP" },
      ],
      correctMatches: {
        1: "C",
        2: "D",
        3: "B",
        4: "A",
      },
    },
    {
      id: 76,
      type: "matching",
      category: "networking",
      question: "Match OSI Layer with Device/Protocol",
      columnA: [
        { key: "1", value: "Layer 3 (Network)" },
        { key: "2", value: "Layer 2 (Data Link)" },
        { key: "3", value: "Layer 7 (Application)" },
      ],
      columnB: [
        { key: "A", value: "Switch" },
        { key: "B", value: "Router" },
        { key: "C", value: "HTTP / Browser" },
      ],
      correctMatches: {
        1: "B",
        2: "A",
        3: "C",
      },
    },
    {
      id: 192,
      type: "matching",
      category: "crypto",
      question: "Match Column A (Rule) with Column B (Example output)",
      columnA: [
        { key: "A", value: "Shift letters +2 : CALL" },
        { key: "B", value: "Reverse alphabet (A=26…Z=1) : DATE" },
        { key: "C", value: "Remove vowels then reverse : MANGOES" },
        { key: "D", value: "(letters)(vowels) format : PEACE" },
        { key: "E", value: "Letter+frequency : BALLOON" },
      ],
      columnB: [
        { key: "1", value: "ECNN" },
        { key: "2", value: "SNGM" },
        { key: "3", value: "52" },
        { key: "4", value: "B1A1L2O2N1" },
        { key: "5", value: "23-7-26-22" },
      ],
      correctMatches: {
        A: "1",
        B: "5",
        C: "2",
        D: "3",
        E: "4",
      },
    },
    {
      id: 193,
      type: "matching",
      category: "crypto",
      question: "Match the number to its symbol-code (1→%, 2→!, 3→#, 4→$, 5→^)",
      columnA: [
        { key: "A", value: "123" },
        { key: "B", value: "451" },
        { key: "C", value: "345" },
        { key: "D", value: "212" },
        { key: "E", value: "531" },
      ],
      columnB: [
        { key: "1", value: "#$^" },
        { key: "2", value: "%!#" },
        { key: "3", value: "^#%" },
        { key: "4", value: "!$%" },
        { key: "5", value: "!%!" },
      ],
      correctMatches: {
        A: "2",
        B: "4",
        C: "1",
        D: "5",
        E: "3",
      },
    },
    {
      id: 194,
      type: "matching",
      category: "crypto",
      question:
        "Match the operator-meaning set to the evaluated result (@=+, #=−, $=×, *=÷)",
      columnA: [
        { key: "A", value: "9 $ 2 @ 6" },
        { key: "B", value: "18 * 3 # 2" },
        { key: "C", value: "10 @ 6 * 2" },
        { key: "D", value: "20 # 8 $ 1" },
        { key: "E", value: "16 * 2 @ 3" },
      ],
      columnB: [
        { key: "1", value: "5" },
        { key: "2", value: "8" },
        { key: "3", value: "11" },
        { key: "4", value: "24" },
        { key: "5", value: "3" },
      ],
      correctMatches: {
        A: "4",
        B: "1",
        C: "3",
        D: "2",
        E: "5",
      },
    },
    {
      id: 195,
      type: "matching",
      category: "crypto",
      question: "Match the word to its (letters)(vowels) code",
      columnA: [
        { key: "A", value: "TRAIN" },
        { key: "B", value: "NOTE" },
        { key: "C", value: "QUEUE" },
        { key: "D", value: "SKY" },
        { key: "E", value: "IDEA" },
      ],
      columnB: [
        { key: "1", value: "52" },
        { key: "2", value: "42" },
        { key: "3", value: "54" },
        { key: "4", value: "30" },
        { key: "5", value: "41" },
      ],
      correctMatches: {
        A: "1",
        B: "2",
        C: "3",
        D: "4",
        E: "5",
      },
    },
    {
      id: 196,
      type: "matching",
      category: "crypto",
      question:
        "Match the '+1 shift' coding (Each letter becomes next: A→B, Z→A)",
      columnA: [
        { key: "A", value: "STOP" },
        { key: "B", value: "GO" },
        { key: "C", value: "CALL" },
        { key: "D", value: "DATE" },
        { key: "E", value: "ZOO" },
      ],
      columnB: [
        { key: "1", value: "HP" },
        { key: "2", value: "TUPQ" },
        { key: "3", value: "EBUF" },
        { key: "4", value: "DBMM" },
        { key: "5", value: "APP" },
      ],
      correctMatches: {
        A: "2",
        B: "1",
        C: "4",
        D: "3",
        E: "5",
      },
    },
    {
      id: 197,
      type: "truefalse",
      category: "crypto",
      question: "If A=1…Z=26, then PEACE has higher sum than DATE. (T/F)",
      correctAnswer: "True",
      points: 1,
    },
    {
      id: 198,
      type: "truefalse",
      category: "crypto",
      question:
        "In code-language type questions, the common code between two statements usually indicates the common word. (T/F)",
      correctAnswer: "True",
      points: 1,
    },
    {
      id: 199,
      type: "truefalse",
      category: "crypto",
      question:
        "If all operators are swapped (+↔÷ and −↔×), BODMAS is still applied normally. (T/F)",
      correctAnswer: "True",
      points: 1,
    },
    {
      id: 200,
      type: "truefalse",
      category: "crypto",
      question: "If A=1, B=2, … Z=26, then the sum-code of PEACE is 35. (T/F)",
      correctAnswer: "False",
      points: 1,
    },
    {
      id: 231,
      type: "matching",
      category: "logic",
      question: "Match the movement to the final displacement",
      columnA: [
        { key: "A", value: "10N, 5E, 10S" },
        { key: "B", value: "4E, 3N, 4W" },
        { key: "C", value: "6N, 6E" },
        { key: "D", value: "8W, 2S" },
        { key: "E", value: "5S, 12E, 5N" },
      ],
      columnB: [
        { key: "1", value: "6 m NE" },
        { key: "2", value: "5 m East" },
        { key: "3", value: "3 m North" },
        { key: "4", value: "8 m West & 2 m South" },
        { key: "5", value: "12 m East" },
      ],
      correctMatches: {
        A: "2",
        B: "3",
        C: "1",
        D: "4",
        E: "5",
      },
    },
    {
      id: 232,
      type: "matching",
      category: "logic",
      question: "Match the position relation to the direction",
      columnA: [
        { key: "A", value: "X is north of Y" },
        { key: "B", value: "X is east of Y" },
        { key: "C", value: "X is south-west of Y" },
        { key: "D", value: "X is north-east of Y" },
        { key: "E", value: "X is west of Y" },
      ],
      columnB: [
        { key: "1", value: "Y is south of X" },
        { key: "2", value: "Y is west of X" },
        { key: "3", value: "Y is north-east of X" },
        { key: "4", value: "Y is south-west of X" },
        { key: "5", value: "Y is east of X" },
      ],
      correctMatches: {
        A: "1",
        B: "2",
        C: "3",
        D: "4",
        E: "5",
      },
    },
    {
      id: 233,
      type: "matching",
      category: "logic",
      question: "Match the rank statement to the rank-from-bottom",
      columnA: [
        { key: "A", value: "5th from top in 30" },
        { key: "B", value: "12th from top in 40" },
        { key: "C", value: "1st from top in 25" },
        { key: "D", value: "9th from top in 50" },
        { key: "E", value: "18th from top in 60" },
      ],
      columnB: [
        { key: "1", value: "26th from bottom" },
        { key: "2", value: "29th from bottom" },
        { key: "3", value: "25th from bottom" },
        { key: "4", value: "42nd from bottom" },
        { key: "5", value: "43rd from bottom" },
      ],
      correctMatches: {
        A: "2",
        B: "3",
        C: "1",
        D: "5",
        E: "4",
      },
    },
    {
      id: 234,
      type: "matching",
      category: "logic",
      question: "Match the series to its next term",
      columnA: [
        { key: "A", value: "2, 5, 8, 11, __" },
        { key: "B", value: "1, 4, 9, 16, __" },
        { key: "C", value: "10, 7, 4, 1, __" },
        { key: "D", value: "3, 6, 12, 24, __" },
        { key: "E", value: "5, 8, 14, 23, __" },
      ],
      columnB: [
        { key: "1", value: "14" },
        { key: "2", value: "25" },
        { key: "3", value: "-2" },
        { key: "4", value: "48" },
        { key: "5", value: "35" },
      ],
      correctMatches: {
        A: "1",
        B: "2",
        C: "3",
        D: "4",
        E: "5",
      },
    },
    {
      id: 235,
      type: "matching",
      category: "logic",
      question:
        "Match the coded instruction to final distance from start (Assume each letter = 1 step: N,S,E,W)",
      columnA: [
        { key: "A", value: "NNEESS" },
        { key: "B", value: "NNNW" },
        { key: "C", value: "EEE" },
        { key: "D", value: "NSNS" },
        { key: "E", value: "WW" },
      ],
      columnB: [
        { key: "1", value: "0" },
        { key: "2", value: "2" },
        { key: "3", value: "3" },
        { key: "4", value: "4" },
        { key: "5", value: "1" },
      ],
      correctMatches: {
        A: "2",
        B: "4",
        C: "3",
        D: "1",
        E: "2",
      },
    },
    {
      id: 236,
      type: "truefalse",
      category: "logic",
      question:
        "If two people face north, 'left' always means west direction. (T/F)",
      correctAnswer: "True",
      points: 1,
    },
    {
      id: 237,
      type: "truefalse",
      category: "logic",
      question:
        "If X is north of Y and Y is north of Z, then X is north of Z. (T/F)",
      correctAnswer: "True",
      points: 1,
    },
    {
      id: 238,
      type: "truefalse",
      category: "logic",
      question:
        "In a class of 50, rank 1 from top is rank 50 from bottom. (T/F)",
      correctAnswer: "True",
      points: 1,
    },
    {
      id: 239,
      type: "truefalse",
      category: "logic",
      question:
        "In series 7,17,15,25,23,… the pattern is +10, −2 repeating. (T/F)",
      correctAnswer: "True",
      points: 1,
    },
    {
      id: 240,
      type: "truefalse",
      category: "logic",
      question:
        "If P is to the south-west of Q, then Q is to the north-east of P. (T/F)",
      correctAnswer: "True",
      points: 1,
    },
  ],
};

module.exports = { securityQuestions };
